[project]
name = "demo"
version = "0.1.0"
description = "Demo Wagtail site using sites_faciles"
readme = "README.md"
requires-python = ">=3.11, <4.0"
dependencies = [
    "wagtail-dsfr",
]

[tool.uv.sources]
wagtail-dsfr = { path = "../wagtail_dsfr", editable = true }
